# Generated by Django 4.1.7 on 2023-02-23 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_categorie', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'categorie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('url', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('nom_image', models.CharField(blank=True, max_length=50, null=True)),
                ('id_categorie', models.ForeignKey(blank=True, db_column='id_categorie', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_images.categorie')),
            ],
            options={
                'db_table': 'image',
                'managed': True,
            },
        ),
    ]
