# Generated by Django 4.1.7 on 2023-02-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_categorie', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'categorie',
                'managed': True,
            },
        ),
    ]
