# Generated by Django 4.1.7 on 2023-02-23 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('url', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('nom_image', models.CharField(blank=True, max_length=50, null=True)),
                ('id_categorie', models.ForeignKey(db_column='id_categorie', on_delete=django.db.models.deletion.DO_NOTHING, to='app_images.categorie')),
            ],
            options={
                'db_table': 'image',
                'managed': True,
            },
        ),
    ]
