# Generated by Django 4.1.7 on 2023-02-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_images', '0003_alter_image_id_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id_categorie',
            field=models.ForeignKey(blank=True, db_column='id_categorie', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_images.categorie'),
        ),
    ]
