# Generated by Django 4.1.7 on 2023-02-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id_modele', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_modele', models.CharField(blank=True, max_length=50, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('recall', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('statut', models.BooleanField(blank=True, null=True)),
                ('date_fin_entrainement', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modele',
                'managed': True,
            },
        ),
    ]
