# Generated by Django 4.1.7 on 2023-02-23 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id_modele', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url_modele', models.CharField(blank=True, max_length=500, null=True)),
                ('nom_modele', models.CharField(blank=True, max_length=50, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('recall', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('statut', models.BooleanField(blank=True, null=True)),
                ('date_fin_entrainement', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modele',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Detailsmodele',
            fields=[
                ('id_modele', models.OneToOneField(db_column='id_modele', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='modeles.modele')),
                ('id_categorie', models.ForeignKey(db_column='id_categorie', on_delete=django.db.models.deletion.DO_NOTHING, to='app_images.categorie')),
            ],
            options={
                'db_table': 'detailsmodele',
                'managed': True,
                'unique_together': {('id_modele', 'id_categorie')},
            },
        ),
    ]
