# Generated by Django 4.1.7 on 2023-02-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeles', '0002_detailsmodele'),
    ]

    operations = [
        migrations.AddField(
            model_name='modele',
            name='url_modele',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
